import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/app/components/HEADER";
import Footer from "@/app/components/FOOTER";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}